name = input()
name2 = input()
name3 = input()
name4 = input()
gpa = int(input())
gpa2 = int(input())
gpa3 = int(input())
gpa4 = int(input())
avg = ((gpa + gpa2 + gpa3 + gpa4)/4)
print(name,name2,name3,name4)
print('their average gpa is', avg)